language: objective-c
before_install:
    - cd Example
    - pod install
script: xcodebuild -workspace LRImageManagerExample.xcworkspace -scheme LRImageManagerExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
